path: C:\Users\hecto\Documents\legoAI\Annotations
train: images/train
val: images/train

names:
  0: dog
  1: person
  2: cat
  3: tv
  4: car
  5: meatballs
  6: marinara sauce
  7: tomato soup
  8: chicken noodle soup
  9: french onion soup
  10: chicken breast
  11: ribs
  12: pulled pork
  13: hamburger
  14: cavity
  15: 2x6
  16: 2x7
  17: 3x3232
  18: 1x4
